server:
  port: 3500
  servlet:
    context-path: /storage
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      remote-ip-header: X-Forwarded-For

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: central-storage
    secret: AkJSi2kmH7vSO5lJcvY
    version: @{ project.version }@

logging:
  config: classpath:logback-http.xml

central:
  logging:
    http:
      #      server: lb://central-logging
      path: central
      code: ${spring.application.name}
      secret: ${spring.application.secret}
  probe:
    authorizer:
      type: fixed
      params:
        secret: cyLfRYFSnhHOpqAAzFyqvCpOwnlIyzJcCUIQqYHSKaOcnTqtiBjhOvKLNasivqjI
    points:
      - name: centralProviderEndpoint
        type: http
        params:
          url: http://central-provider/provider/__probe
          headers:
            - name: Authorization
              value: ${central.probe.authorizer.params.secret}
