server:
  servlet:
    context-path: /logging
  port: 3400

spring:
  application:
    name: central-provider
    version: @{ project.version }@

central:
  provider:
    fetchers:
      - SAAS
      - LOG