server:
  port: 3200
  servlet:
    context-path: /provider

spring:
  application:
    name: central-provider
  datasource:
    name: master
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/centralx?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

# 应用配置
studio:
  provider:
    code: central-provider
    key: central-provider-key
