server:
  port: 3200

spring:
  application:
    name: central-provider
  datasource:
    name: master
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./central-provider
    username: centralx
    password: central.x

# 应用配置
app:
  provider:
    code: central-provider
    key: central-provider-key
