server:
  port: 3300
  servlet:
    context-path: /provider

spring:
  application:
    name: central-provider
    version: @{ project.version }@
  datasource:
    name: master
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/centralx?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

logging:
  config: classpath:logback-http.xml

# 应用配置
studio:
  provider:
    code: central-provider
    key: central-provider-key
    fetchers:
      - log
      - saas
