server:
  port: 3200
  servlet:
    context-path: /security
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      remote-ip-header: X-Forwarded-For

spring:
  application:
    name: central-security
    secret: AkJSi2kmH7vSO5lJcvY
    version: @{ project.version }@

logging:
  config: classpath:logback-http.xml

central:
  logging:
    http:
#      server: lb://central-logging
      path: central
      code: ${spring.application.name}
      secret: ${spring.application.secret}
