name: Release

on:
  push:
    branches:
      - master
      - '*.x'
jobs:
  # 编译类库并发布到 GitHub Packages
  release-libraries-to-github-packages:
    name: Release Libraries to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Echo settings.xml
        run: cat /home/runner/.m2/settings.xml
      - name: Release packages
        run: mvn -P github --batch-mode clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.GHPKG_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GHPKG_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  # 编译类库并发布到 Maven Central
  release-libraries-to-maven-central:
    name: Release Libraries to Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Echo settings.xml
        run: cat /home/runner/.m2/settings.xml
      - name: Release packages
        run: mvn -P sonatype --batch-mode clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  # 构建应用组件并发布 Docker 镜像
  release-studio-images:
    name: Release Docker Images
    runs-on: ubuntu-latest
    needs: [release-libraries-to-github-packages, release-libraries-to-maven-central]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Set up Docker(QEMU)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker(Buildx)
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHPKG_USERNAME }}
          password: ${{ secrets.GHPKG_TOKEN }}
      - name: Build packages
        run: mvn -P github clean package
        env:
          MAVEN_USERNAME: ${{ secrets.GHPKG_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GHPKG_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Release to DockerHub
        uses: docker/bake-action@v5
        with:
          push: true
        env:
          REGISTRY: docker.io
          REPOSITORY: centralx
      - name: Release to GitHub Packages
        uses: docker/bake-action@v5
        with:
          push: true
        env:
          REGISTRY: ghcr.io
          REPOSITORY: central-x